apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc              # Specify name for PVC. This name should match with the pvc name specified in the Postgres deployment config file
spec:
  storageClassName: manual
  volumeName: postgres-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
