apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server     # This label has been set in the deployment for the Server POD's. Format is <selector>:<label> You can set - env:prod, env:dev, db:prod, db:dev, app:frontend, app:backend, component:web, component:db and etc ... ... 
  ports:
  - port: 5000
    targetPort: 5000
