apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: rkdba-com-tls
spec:
  secretName: rkdba-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: rkdba.com
  dnsNames:
    - rkdba.com
    - www.rkdba.com