apiVersion: apps/v1                                   # API Version
kind: Deployment                                      # k8s object type that will be deployed by this file
metadata:
  name: worker-deployment                             # This name will be used as deployment name, and the name of the pod's that will be contorolled by this deployment
spec:
  replicas: 3                                         # Number of replicas that deployment should keep up
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      component: worker                               # This label should match with the label in of 'template' section. k8s will controll all POD's that has this label
  template:
    metadata:
      labels:                                         # Deployment will controll any POD's that has follwing label. This label should match with the label in the 'selector' section.
        component: worker                             # Format is <selector>:<label> You can set - env:prod, env:dev, db:prod, db:dev, app:frontend, app:backend, component:web, component:db and etc ...
    spec:                                             # Following configuration if related to container only
      containers: 
      - name: worker                                  # Set your name for container that will run inside of POD
        image: ravilkhalilov/multi-worker             # Which docker image will be pulled from Docker Hub as POD container image
        resources:
          limits:
            memory: "128Mi"                           # Provide 128Mi of total Worker Node RAM to container
            cpu: "64m"                               # Provide 500m of total Worker Node CPU to container
        env:                                          # Set environment variables for this container, that can be used to connect to Redis POD
          - name: REDIS_HOST                          # Name of the environment variable fo Redis Host
            value: redis-cluster-ip-service           # Set the Redis Cluster IP Service from the output of 'kubectl get svc' command, as the value of the environment variable.
          - name: REDIS_PORT                          # Name of the environment variable fo Redis Port
            value: "6379"                             # Set the Redis Port as the value for the environment variable.  NOTE: port must be enclosed in bouble quotes
