name: Deploy MultiK8s

on:
  push:
    branches: [ "main" ]
 
env:
  SHA: $(git rev-parse HEAD)
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Test
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ravilkhalilov/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true ravilkhalilov/react-test npm test
 
      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
 
      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: supple-design-372120
 
      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker
 
      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: us-central1-c
 
      - name: Build
        run: |-
          docker build -t ravilkhalilov/multi-client:latest -t ravilkhalilov/multi-client:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t ravilkhalilov/multi-server:latest -t ravilkhalilov/multi-server:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t ravilkhalilov/multi-worker:latest -t ravilkhalilov/multi-worker:${{ env.SHA }} -f ./worker/Dockerfile ./worker
 
      - name: Push
        run: |-
          docker push ravilkhalilov/multi-client:latest
          docker push ravilkhalilov/multi-server:latest
          docker push ravilkhalilov/multi-worker:latest
 
        #  docker push ravilkhalilov/multi-client:${{ env.SHA }}
        #  docker push ravilkhalilov/multi-server:${{ env.SHA }}
        #  docker push ravilkhalilov/multi-worker:${{ env.SHA }}
 
      - name: Apply
        run: |-
          kubectl apply -f k8s
        # kubectl set image deployments/server-deployment server=ravilkhalilov/multi-server:${{ env.SHA }}
        # kubectl set image deployments/client-deployment client=ravilkhalilov/multi-client:${{ env.SHA }}
        # kubectl set image deployments/worker-deployment worker=ravilkhalilov/multi-worker:${{ env.SHA }}